# -*- coding: utf-8 -*-
"""build_city_zip_map.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xeSx6ARA-E8yxciwMoiLkTyaBGEhLB3k
"""

from pathlib import Path

import geopandas as gpd


def main() -> None:
    # -------------------------------------------------
    # Paths
    # -------------------------------------------------
    DATA_DIR = Path("data/raw/census/tiger/2023")
    OUTPUT_DIR = Path("data/processed/geo")
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    place_zip = DATA_DIR / "place" / "tl_2023_51_place.zip"
    zcta_zip  = DATA_DIR / "zcta520" / "tl_2023_us_zcta520.zip"

    # -------------------------------------------------
    # Load shapefiles directly from ZIPs
    # -------------------------------------------------
    place = gpd.read_file(f"zip://{place_zip}!tl_2023_51_place.shp")
    zcta  = gpd.read_file(f"zip://{zcta_zip}!tl_2023_us_zcta520.shp")

    print("Shapefiles loaded successfully.")

    # -------------------------------------------------
    # Filter target cities
    # -------------------------------------------------
    target_cities = [
        "Portsmouth",
        "Norfolk",
        "Virginia Beach",
        "Suffolk",
        "Chesapeake",
    ]

    cities = place[
        place["NAME"].str.lower().isin([c.lower() for c in target_cities])
    ]

    # -------------------------------------------------
    # CRS alignment
    # -------------------------------------------------
    zcta = zcta.to_crs(cities.crs)

    # -------------------------------------------------
    # Spatial join: ZCTAs within cities
    # -------------------------------------------------
    city_zips = gpd.sjoin(
        zcta,
        cities,
        how="inner",
        predicate="intersects",
    )

    # -------------------------------------------------
    # Outputs
    # -------------------------------------------------
    csv_path = OUTPUT_DIR / "city_zip_map.csv"
    geojson_path = OUTPUT_DIR / "city_zip_map.geojson"

    (
        city_zips[["NAME", "ZCTA5CE20"]]
        .drop_duplicates()
        .sort_values(["NAME", "ZCTA5CE20"])
        .to_csv(csv_path, index=False)
    )

    city_zips.to_file(geojson_path, driver="GeoJSON")

    print(f"Saved CSV: {csv_path}")
    print(f"Saved GeoJSON: {geojson_path}")


if __name__ == "__main__":
    main()