# -*- coding: utf-8 -*-
"""run_simulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/185-DltIYsfklD8jI0A9phKC8gjWBt1KR
"""

from __future__ import annotations

from pathlib import Path
import numpy as np

from src.ingestion.build_zip_df import build_zip_df
from src.simulation.finaid_sim import simulate_many_years


def main() -> None:
    # Inputs (produced by your earlier steps)
    city_zip_csv = Path("data/processed/geo/city_zip_map.csv")

    # You’ll put these ACS exports under data/raw/acs/ (recommended)
    acs_detailed_csv = Path("data/raw/acs/acs_2023_acs5_zcta_detailed.csv")
    acs_profile_csv = Path("data/raw/acs/acs_2023_acs5_zcta_profile.csv")

    target_city_weights = {
        "Virginia Beach": 0.63,
        "Norfolk": 0.21,
        "Chesapeake": 0.10,
        "Suffolk": 0.02,
        "Portsmouth": 0.02,
    }

    zip_df = build_zip_df(
        city_zip_csv=city_zip_csv,
        acs_detailed_csv=acs_detailed_csv,
        acs_profile_csv=acs_profile_csv,
        target_city_weights=target_city_weights,
        seed=42,
    )

    sim_df = simulate_many_years(
        n_years=10,
        applicants_per_year=250,
        zip_df=zip_df,
        base_seed=42,
    )
    sim_df["data_type"] = "simulated"

    out_dir = Path("data/processed/sim")
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "finaid_sim.csv"
    sim_df.to_csv(out_path, index=False)

    print(f"Saved simulation to: {out_path}")


if __name__ == "__main__":
    main()